/**
 * THE NEWSTON - Automated Fetcher
 * Columns: id, title, category, excerpt, url, imageUrl, author, readTime, date, source
 */

const { createClient } = require('@supabase/supabase-js');

console.log("--- STARTING TERMINAL SYNC ---");

// 1. Initialize Supabase
const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY
);

async function runAutomation() {
  try {
    const apiKey = process.env.NEWS_API_KEY;
    console.log("📡 Connecting to NewsAPI...");

    const response = await fetch(
      `https://newsapi.org/v2/top-headlines?category=business&language=en&apiKey=${apiKey}`
    );

    if (!response.ok) {
      throw new Error(`NewsAPI returned ${response.status}: ${response.statusText}`);
    }

    const data = await response.json();
    const articles = data.articles || [];

    console.log(`✅ API Response received. Found ${articles.length} articles.`);

    // 2. Map API data to your EXACT 10 columns
    const newsData = articles.map((article) => ({
      // id is usually generated by Supabase (UUID), so we don't include it here unless you want to
      title: article.title || 'Untitled',
      category: 'Finance',
      excerpt: article.description || 'No description available.',
      url: article.url,
      imageUrl: article.urlToImage || 'https://images.unsplash.com/photo-1611974714851-48206138d73e',
      author: article.author || 'Staff Writer',
      readTime: '3 min read',
      date: article.publishedAt || new Date().toISOString(),
      source: article.source.name || 'Financial News'
    }));

    console.log("💾 Upserting to Supabase...");

    // 3. Upsert based on URL to prevent duplicates
    // Note: Column sequence in DB doesn't matter, only the key names.
    const { error } = await supabase
      .from('news')
      .upsert(newsData, { onConflict: 'url' });

    if (error) {
      console.error("❌ SUPABASE ERROR:", error.message);
      throw error;
    }

    console.log("🚀 SUCCESS: 10 columns synced and terminal updated.");

  } catch (err) {
    console.error("--- CRITICAL FAILURE ---");
    console.error(err.message);
    process.exit(1); // Forces GitHub Action to show a Red X
  }
}

runAutomation();
